name: CI/CD

on:
  push:
    branches:
      - release/CL-150

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set environment variables
      run: |
        echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
        echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV

    - name: Run deploy script
      run: |
        cd infra/terraform
        bash deploy.sh 637190323689 ap-northeast-3 dev

    - name: Wait for a moment
      run: sleep 30  # 30秒待機

    - name: Get API Gateway endpoint URL
      run: |
        endpoint_url=$(terraform output api_gateway_endpoint)
        echo $endpoint_url > endpoint.txt

    - name: Upload endpoint URL as artifact
      uses: actions/upload-artifact@v2
      with:
        name: endpoint-url
        path: endpoint.txt

    - name: Check the content of endpoint.txt
      run: cat endpoint.txt

  test:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with:
        name: endpoint-url

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    # API Gatewayエンドポイントのテスト
    - name: Test API Gateway endpoint using curl
      run: |
        endpoint_url=$(cat endpoint.txt)
        response=$(curl -X PUT $endpoint_url -H "Content-Type: application/json; charset=UTF-8" -d "{\"userId\":\"example@email.com\",\"mDt\":\"2021-12-31T23:59:59.999Z\",\"lat\":\"35.6895\",\"lng\":\"139.6917\",\"speed\":10,\"driveMode\":1,\"charge\":80,\"driveUnitErr\":\"00000000\",\"lockState\":true,\"lockId\":\"XXX0000\",\"lockErr\":\"00000000\"}")
        
        # 応答に期待するキーが含まれているかをチェックする
        echo "$response" | grep '"userId"'
        echo "$response" | grep '"rDt"'

