name: CD

on:
  push:
    branches:
      - release/CL-150  # release/CL-150ブランチへのpushをトリガーとする

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set environment variables
      run: |
        echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
        echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV

    - name: Run deploy script
      run: |
        cd infra/terraform
        bash deploy.sh 637190323689 ap-northeast-3 dev

