name: CD

on:
  push:
    branches:
      - release/CL-150

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set environment variables
      run: |
        echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
        echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV

    - name: Run deploy script
      run: |
        cd infra/terraform
        bash deploy.sh 637190323689 ap-northeast-3 dev

    - name: Wait for a moment
      run: sleep 120  # 120秒待機

    - name: Extract API Gateway endpoint URL from terraform.tfstate
      run: |
        base_url=$(jq -r '.resources[] | select(.type=="aws_api_gateway_deployment") | .instances[0].attributes.invoke_url' infra/terraform/terraform.tfstate)
        path_part=$(jq -r '.resources[] | select(.type=="aws_api_gateway_resource") | .instances[0].attributes.path_part' infra/terraform/terraform.tfstate)
        endpoint_url="${base_url}/${path_part}"
        echo $endpoint_url > endpoint.txt

    - name: Upload endpoint.txt as artifact
      uses: actions/upload-artifact@v2
      with:
        name: endpoint-url
        path: endpoint.txt

