name: CI/CD

on:
  push:
    branches:
      - release/CL-150

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Extract API Gateway endpoint URL from terraform.tfstate
      run: |
        base_url=$(jq -r '.resources[] | select(.type=="aws_api_gateway_deployment") | .instances[0].attributes.invoke_url' infra/terraform/terraform.tfstate)
        path_part=$(jq -r '.resources[] | select(.type=="aws_api_gateway_resource") | .instances[0].attributes.path_part' infra/terraform/terraform.tfstate)
        endpoint_url="${base_url}/${path_part}"
        echo $endpoint_url > endpoint.txt

    - name: Upload endpoint.txt as artifact
      uses: actions/upload-artifact@v2
      with:
        name: endpoint-url
        path: endpoint.txt

  test:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Download endpoint.txt artifact
      uses: actions/download-artifact@v2
      with:
        name: endpoint-url

    - name: Test API Gateway endpoint using curl
      run: |
        endpoint_url=$(cat endpoint.txt)
        response=$(curl -X PUT $endpoint_url -H "Content-Type: application/json; charset=UTF-8" -d "{\"userId\":\"example@email.com\",\"mDt\":\"2021-12-31T23:59:59.999Z\",\"lat\":\"35.6895\",\"lng\":\"139.6917\",\"speed\":10,\"driveMode\":1,\"charge\":80,\"driveUnitErr\":\"00000000\",\"lockState\":true,\"lockId\":\"XXX0000\",\"lockErr\":\"00000000\"}")
        
        # 応答に期待するキーが含まれているかをチェックする
        echo "$response" | grep '"userId"'
        echo "$response" | grep '"rDt"'

