name: CD

on:
  push:
    branches:
      - release/CL-150

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Run deploy script
      run: |
        cd infra/terraform
        bash deploy.sh 637190323689 ap-northeast-3 dev

    - name: Fetch API Gateway endpoint
      id: fetch_endpoint
      run: echo "::set-output name=url::$(terraform output api_gateway_endpoint_url)"

    - name: Upload endpoint URL as artifact
      uses: actions/upload-artifact@v2
      with:
        name: endpoint-url
        path: ${{ steps.fetch_endpoint.outputs.url }}

